### ISSUE TITLE
有些应用会提示“未连接到互联网”，实际上可以连接使用。

### ISSUE THREAD

**Issue by JhihYuWong** [fa1se/fake-gsm-sim-operator#1]
（偶发）有些应用会提示“未连接到互联网”，实际上可以连接使用。
例如：YouTube、Chrome、Netfilx

**Comment by fa1se** [comment]
似乎是与模块无关的网络问题。

**Comment by cccClyde** [comment]
我也没遇到这情况，建议排查下网络环境问题。

**Comment by JhihYuWong** [comment]
> 我也没遇到这情况，建议排查下网络环境问题。
除了刚安装模块的那两天有遇到，其他时间还没出现过。
