### ISSUE TITLE
移动数据丢失的可能解决方案

### ISSUE THREAD

**Issue by cccClyde** [fa1se/fake-gsm-sim-operator#2]
开发者你好，

你的模块在 Android 11 上确认有效，但我和身边的朋友都遇到了移动数据不可用、APN 配置丢失以及偶发的人脸识别不可用（Pixel 4，不确定是否为 Android 11 的问题）。

仔细对比 Android 10 可用的 riru-location模块之后我发现两边最大的差别在于**gsm.sim.operator.alpha, default to Verizon** 这一项。

怀疑这个会对国内运营商 SIM 卡的移动数据使用产生影响，建议测试确认下看要不要移除。

---

Update

尝试自行移除 gsm.sim.operator.alpha 这一段之后依然存在移动数据连接丢失的情况。

**Comment by darkmoon** [comment]
One plus 8T，android 11，的确出现移动数据不可用，apn丢失，且无法在设置中添加后保存。good news是居然打开了rcs，verizon立功了？

**Comment by fa1se** [comment]
@cccClyde 没有在Adnroid 11测试过。可以尝试把`gsm.sim.operator.numeric`改成`310030`（也就是[GhostFlying/LocationReportEnabler](https://github.com/GhostFlying/LocationReportEnabler)的行为）。至于`gsm.sim.operator.alpha`，那是随便加的，可以去掉。
@darkmoon Messages似乎会尝试开启RCS，不确定其中原因。
